# Generated by Django 2.1.4 on 2020-02-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
