# Generated by Django 2.2.3 on 2020-02-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0007_course_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='sgapp.Tag'),
        ),
    ]
