# Generated by Django 2.2.3 on 2020-02-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0008_auto_20200224_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Follow_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=30, null=True)),
                ('eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgapp.Course')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgapp.Follow')),
            ],
        ),
    ]
