# Generated by Django 2.2.3 on 2020-02-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0009_follow_follow_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow_post',
            name='eval',
        ),
        migrations.RemoveField(
            model_name='follow_post',
            name='follow',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Follow_post',
        ),
    ]
