# Generated by Django 2.2.3 on 2020-02-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0010_auto_20200224_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tname',
        ),
    ]
