# Generated by Django 2.1.4 on 2020-02-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0012_profile_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='author',
        ),
    ]
